export const ERROR_RECEIVE_CATEGORIES = 'ERROR_RECEIVE_CATEGORIES'
export const REQUEST_RECEIVE_CATEGORIES = 'REQUEST_RECEIVE_CATEGORIES'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'

export const ERROR_DELETE_CATEGORY = 'ERROR_DELETE_CATEGORY'

export const REQUEST_DELETE_CATEGORY = 'REQUEST_DELETE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'